### ISSUE TITLE
Add backup rotation scheme

### ISSUE THREAD

**Issue by payamQorbanpour** [gobackup/gobackup-operator#19]
Set a strategy to remove old backups with setting count limits for amount of backups.

**Comment by payamQorbanpour** [comment]
```yaml
apiVersion: gobackup.io/v1
kind: Backup
metadata:
  name: example-backup
model:
  backupModelRef:
    name: "example-backupmodel"
  storageRefs:
    - apiGroup: "storage.gobackup.io"
      type: "S3"
      name: "example-s3"
      keep: 5
      timeout: 30
```

Adding `keep: <number>`  in backup manifest will do the job,
